### ISSUE TITLE
pull request

### ISSUE THREAD

**Issue by Hamidreza-Fakharzadeh** [CodeYourFuture/tv-show-dom-project#2]

**Comment by nbogie** [comment]
Thanks Hamidreza, I imagine you were intending to draw attention to Ahmad's PR to fix the bad link to the instructions?  That'll be fixed by other means in the morning.
When registering issues on github it's important to give a clear title and description of the problem.  
For now, I've closed this one!

**Comment by Hamidreza-Fakharzadeh** [comment]
Hi Neill, thank you for informing and sorry to cause the problem. I thought
I should make a pull request then I found that it is a template which is my
own root repository. It is my first time I used issue tab and I did not
know how to do it.

Regards
Hamidreza Fakharzadeh
